#!/bin/bash
#
# Gmail Skill - Installer
#
# Usage: ./install.sh [PROJECT_NAME] [TARGET_DIR]
#
# This script installs ccskill-gmail to a project directory.
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo "================================================"
echo "  Gmail Skill - Installer"
echo "================================================"
echo ""

# ========================================
# 1. 引数検証
# ========================================

# 第1引数: PROJECT_NAME（オプション）
# 第2引数: TARGET_DIR（オプション）
PROJECT_NAME_INPUT="${1:-}"
TARGET_DIR="${2:-.}"

# 絶対パスに変換
if [ ! -d "$TARGET_DIR" ]; then
    echo -e "${RED}Error: TARGET_DIR does not exist: $TARGET_DIR${NC}"
    exit 1
fi

TARGET_DIR=$(cd "$TARGET_DIR" && pwd)

# プロジェクト名の決定
if [ -z "$PROJECT_NAME_INPUT" ] || [ "$PROJECT_NAME_INPUT" = "-" ]; then
    # 未指定または "-" の場合はディレクトリ名を使用
    PROJECT_NAME=$(basename "$TARGET_DIR")
else
    PROJECT_NAME="$PROJECT_NAME_INPUT"
fi

GAS_PROJECT_TITLE="Gmail Skill - $PROJECT_NAME"

echo "Installing to: $TARGET_DIR"
echo "GAS Project Title: $GAS_PROJECT_TITLE"
echo ""

# ========================================
# 2. 環境変数チェック
# ========================================

if [ -z "$CCSKILL_GMAIL_DIR" ]; then
    echo -e "${RED}Error: CCSKILL_GMAIL_DIR is not set${NC}"
    echo ""
    echo "Please set the environment variable:"
    echo "  export CCSKILL_GMAIL_DIR=/path/to/ccskill-gmail"
    echo ""
    echo "Add to your ~/.zshrc or ~/.bashrc:"
    echo "  echo 'export CCSKILL_GMAIL_DIR=~/projects/ccskill-gmail' >> ~/.zshrc"
    echo "  source ~/.zshrc"
    exit 1
fi

if [ ! -d "$CCSKILL_GMAIL_DIR" ]; then
    echo -e "${RED}Error: CCSKILL_GMAIL_DIR does not exist: $CCSKILL_GMAIL_DIR${NC}"
    exit 1
fi

# ========================================
# 3. 前提条件チェック
# ========================================

echo "Checking prerequisites..."

# clasp のインストールチェック
if ! command -v clasp &> /dev/null; then
    echo -e "${RED}Error: clasp is not installed${NC}"
    echo ""
    echo "Please install clasp first:"
    echo "  npm install -g @google/clasp"
    echo ""
    echo "Then login to Google:"
    echo "  clasp login"
    exit 1
fi

# clasp ログインチェック
if ! clasp login --status &> /dev/null; then
    echo -e "${YELLOW}You need to login to Google first.${NC}"
    echo "Running: clasp login"
    clasp login
fi

echo -e "${GREEN}✓ Prerequisites checked${NC}"
echo ""

# ========================================
# 4. 既存インストールチェック
# ========================================

SKILL_DIR="$TARGET_DIR/.claude/skills/ccskill-gmail"
GAS_DIR="$TARGET_DIR/.ccskill-gmail"

if [ -d "$SKILL_DIR" ] || [ -d "$GAS_DIR" ]; then
    echo -e "${YELLOW}Warning: Existing installation found${NC}"
    echo ""
    if [ -d "$SKILL_DIR" ]; then
        echo "  - $SKILL_DIR"
    fi
    if [ -d "$GAS_DIR" ]; then
        echo "  - $GAS_DIR"
    fi
    echo ""
    read -p "Overwrite existing installation? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Installation cancelled."
        exit 0
    fi
    echo ""
fi

# ========================================
# 5. スキル定義のコピー
# ========================================

echo "Step 1: Installing skill definition..."

mkdir -p "$SKILL_DIR"

# スキル定義が存在する場合のみコピー
if [ -d "$CCSKILL_GMAIL_DIR/.claude/skills/ccskill-gmail" ] && [ "$(ls -A "$CCSKILL_GMAIL_DIR/.claude/skills/ccskill-gmail" 2>/dev/null)" ]; then
    cp -r "$CCSKILL_GMAIL_DIR/.claude/skills/ccskill-gmail/"* "$SKILL_DIR/" 2>/dev/null || true
fi

# バージョン情報とインストール時刻を取得
VERSION=$(cd "$CCSKILL_GMAIL_DIR" && git rev-parse --short HEAD 2>/dev/null || echo "unknown")
INSTALL_TIME=$(date '+%Y-%m-%d %H:%M:%S')

echo -e "${GREEN}✓ Skill definition installed${NC}"
echo ""

# ========================================
# 6. GASコードのコピー
# ========================================

echo "Step 2: Installing GAS code..."

mkdir -p "$GAS_DIR/src"
cp -r "$CCSKILL_GMAIL_DIR/gas-template/"* "$GAS_DIR/src/"

# .claspignore を GAS_DIR 直下にコピー
if [ -f "$CCSKILL_GMAIL_DIR/gas-template/.claspignore" ]; then
    cp "$CCSKILL_GMAIL_DIR/gas-template/.claspignore" "$GAS_DIR/.claspignore"
fi

# config.js 生成（Gmail は最小構成）
cat > "$GAS_DIR/src/config.js" << EOF
/**
 * Gmail Skill - Configuration
 *
 * This file is generated by install.sh on $INSTALL_TIME
 */

const CONFIG = {
  // Reserved for future use
};
EOF

# メタデータファイル作成
cat > "$GAS_DIR/.ccskill-metadata.json" << EOF
{
  "installed_at": "$INSTALL_TIME",
  "installed_from": "$CCSKILL_GMAIL_DIR",
  "version": "$VERSION",
  "project_name": "$PROJECT_NAME"
}
EOF

echo -e "${GREEN}✓ GAS code installed${NC}"
echo ""

# ========================================
# 7. clasp create & push
# ========================================

echo "Step 3: Creating GAS project..."
echo ""

cd "$GAS_DIR"

# clasp create
clasp create --type standalone --title "$GAS_PROJECT_TITLE"

# .clasp.json の位置を確認・修正
if [ -f "src/.clasp.json" ]; then
    mv src/.clasp.json .clasp.json
fi

# rootDir を設定
if command -v jq &> /dev/null; then
    tmp=$(mktemp)
    jq '.rootDir = "./src"' .clasp.json > "$tmp"
    mv "$tmp" .clasp.json
fi

echo -e "${GREEN}✓ GAS project created${NC}"
echo ""

# clasp push
echo "Pushing code to Google Apps Script..."
clasp push --force

echo -e "${GREEN}✓ Code pushed${NC}"
echo ""

# ========================================
# 8. デプロイ案内
# ========================================

echo "================================================"
echo "  Manual Deployment Required"
echo "================================================"
echo ""
echo "Opening GAS editor..."
echo ""
echo "Please deploy as Web App with the following settings:"
echo ""
echo "  1. Click 'Deploy' > 'New deployment'"
echo "  2. Click the gear icon > Select 'Web app'"
echo "  3. Execute as: 'Me'"
echo "  4. Who has access: 'Anyone' (REQUIRED)"
echo "  5. Click 'Deploy'"
echo ""
echo -e "${YELLOW}NOTE: First deployment will request Gmail permissions.${NC}"
echo -e "${YELLOW}Please authorize access to your Gmail account.${NC}"
echo ""
read -p "Press Enter to open the GAS editor..."

clasp open

echo ""

# ========================================
# 9. エンドポイント検証
# ========================================

echo "================================================"
echo "  Endpoint Verification"
echo "================================================"
echo ""
echo "After deploying, copy the Web App URL from the deployment dialog."
echo "The URL looks like: https://script.google.com/macros/s/XXXXXX/exec"
echo ""

# Function to validate endpoint
validate_endpoint() {
    local url="$1"
    local response

    echo "Testing endpoint..."
    response=$(curl -sL --max-time 60 "$url" 2>/dev/null)

    if [ $? -ne 0 ]; then
        echo -e "${RED}✗ Failed to connect to the endpoint${NC}"
        return 1
    fi

    # Check if response contains expected JSON
    if echo "$response" | grep -q '"ok":true' && echo "$response" | grep -q '"Gmail Skill is running"'; then
        echo -e "${GREEN}✓ Endpoint is working correctly${NC}"
        return 0
    else
        echo -e "${RED}✗ Unexpected response from endpoint${NC}"
        echo "Response: $response"
        return 1
    fi
}

# Loop until valid endpoint is provided
while true; do
    read -p "Enter the Web App URL: " ENDPOINT_URL

    # Basic URL validation
    if [[ ! "$ENDPOINT_URL" =~ ^https://script\.google\.com/macros/s/.+/exec$ ]]; then
        echo -e "${RED}Invalid URL format. Please enter a valid GAS Web App URL.${NC}"
        continue
    fi

    if validate_endpoint "$ENDPOINT_URL"; then
        break
    else
        echo ""
        echo "Please check:"
        echo "  1. The URL is correct"
        echo "  2. The Web App is deployed with 'Anyone' access"
        echo "  3. Gmail permissions are authorized"
        echo ""
        read -p "Try again? (Y/n): " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Nn]$ ]]; then
            echo -e "${YELLOW}Setup incomplete. You can manually add the endpoint to .env later.${NC}"
            exit 0
        fi
    fi
done

echo ""

# ========================================
# 10. .env 保存
# ========================================

echo "Step 4: Saving endpoint to .env..."

ENV_FILE="$TARGET_DIR/.env"

if [ -f "$ENV_FILE" ]; then
    # 既存の .env がある場合
    if grep -q "GMAIL_ENDPOINT" "$ENV_FILE"; then
        # 既にエントリがある場合は更新
        if command -v sed &> /dev/null; then
            sed -i.bak "s|GMAIL_ENDPOINT=.*|GMAIL_ENDPOINT=${ENDPOINT_URL}|" "$ENV_FILE"
            rm -f "$ENV_FILE.bak"
        fi
    else
        # エントリがない場合は追記
        echo "" >> "$ENV_FILE"
        echo "# Gmail Skill" >> "$ENV_FILE"
        echo "GMAIL_ENDPOINT=${ENDPOINT_URL}" >> "$ENV_FILE"
    fi
else
    # .env が存在しない場合は新規作成
    cat > "$ENV_FILE" << EOF
# Gmail Skill
# Generated by install.sh on $INSTALL_TIME
# DO NOT commit this file to version control.

GMAIL_ENDPOINT=${ENDPOINT_URL}
EOF
fi

echo -e "${GREEN}✓ Endpoint saved to .env${NC}"
echo ""

# ========================================
# 11. .gitignore 推奨表示
# ========================================

echo "================================================"
echo "  .gitignore Recommendation"
echo "================================================"
echo ""
echo "Add the following to your project's .gitignore:"
echo ""
echo -e "${YELLOW}# Gmail Skill${NC}"
echo -e "${YELLOW}.ccskill-gmail/${NC}"
echo -e "${YELLOW}.env${NC}"
echo ""

# ========================================
# 完了メッセージ
# ========================================

echo "================================================"
echo -e "${GREEN}  Installation Complete!${NC}"
echo "================================================"
echo ""
echo "Installed to: $TARGET_DIR"
echo ""
echo "You can now use Claude Code to interact with your Gmail."
echo "Try these commands:"
echo ""
echo "  \"Search for unread emails\""
echo "  \"Show me emails from boss@company.com\""
echo "  \"Create a draft reply to the latest email\""
echo ""
echo "To update this skill later:"
echo "  cd $TARGET_DIR"
echo "  \$CCSKILL_GMAIL_DIR/update.sh"
echo ""
